#!/usr/bin/env python3
"""
Generate paper-ready tables and consolidated outputs.
"""
import json
import subprocess
from pathlib import Path

import pandas as pd


def ensure_table4(root: Path) -> tuple[bool, str]:
    """
    Ensure Table 4 comparison output exists.
    Returns (available, message).
    """
    table4_csv = root / "paper_outputs" / "tables" / "table4_method_comparison.csv"
    if table4_csv.exists():
        return True, "Table 4 already exists."

    script = root / "scripts" / "legacy_methods" / "generate_table4_method_comparison.py"
    if not script.exists():
        return False, "Missing legacy comparison script."

    try:
        result = subprocess.run(
            ["python", str(script)],
            cwd=str(root),
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0 and table4_csv.exists():
            return True, "Table 4 generated by legacy comparison script."
        return (
            False,
            "Could not generate Table 4 automatically. "
            "Run Top2Vec scripts first: "
            "scripts/legacy_methods/top2vec_modeling.py and "
            "scripts/legacy_methods/top2vec_validation.py",
        )
    except Exception as exc:  # pragma: no cover
        return False, f"Table 4 generation failed: {exc}"


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    paper_outputs = root / "paper_outputs"
    out_tables = root / "paper_outputs" / "tables"
    out_stats = root / "paper_outputs" / "statistics"
    out_reports = root / "paper_outputs" / "reports"
    out_tables.mkdir(parents=True, exist_ok=True)
    out_stats.mkdir(parents=True, exist_ok=True)
    out_reports.mkdir(parents=True, exist_ok=True)

    topic_info = pd.read_csv(root / "results" / "topics" / "topic_info.csv")
    doc_topics = pd.read_csv(root / "results" / "topics" / "document_topics.csv")
    validation_path = root / "results" / "validation" / "topic_validation_23topics.csv"
    if validation_path.exists():
        topic_validation = pd.read_csv(validation_path)
    else:
        topic_validation = pd.DataFrame()

    table_topics = topic_info[topic_info["Topic"] != -1][["Topic", "Count", "Name"]].copy()
    table_topics.to_csv(out_tables / "table_topics.csv", index=False)

    outlier_n = int((doc_topics["topic"] == -1).sum())
    totals = {
        "total_documents": int(len(doc_topics)),
        "clustered_documents": int((doc_topics["topic"] != -1).sum()),
        "unclustered_documents": outlier_n,
        "unclustered_percent": round(outlier_n / len(doc_topics) * 100, 2),
        "num_topics": int(doc_topics["topic"].nunique() - 1),
    }
    with (out_stats / "core_counts.json").open("w", encoding="utf-8") as f:
        json.dump(totals, f, indent=2)

    if not topic_validation.empty:
        topic_validation.to_csv(out_tables / "table_topic_validation.csv", index=False)

    table4_available, table4_message = ensure_table4(root)

    checklist = {
        "table_topics_csv": (out_tables / "table_topics.csv").exists(),
        "table_topic_validation_csv": (out_tables / "table_topic_validation.csv").exists(),
        "table4_method_comparison_csv": (out_tables / "table4_method_comparison.csv").exists(),
        "table4_method_comparison_md": (out_tables / "table4_method_comparison.md").exists(),
        "core_counts_json": (out_stats / "core_counts.json").exists(),
        "table4_status_message": table4_message,
    }
    with (out_reports / "paper_bundle_checklist.json").open("w", encoding="utf-8") as f:
        json.dump(checklist, f, indent=2)

    lines = [
        "# Paper Bundle Checklist",
        "",
        f"- table_topics.csv: {'OK' if checklist['table_topics_csv'] else 'MISSING'}",
        f"- table_topic_validation.csv: {'OK' if checklist['table_topic_validation_csv'] else 'MISSING'}",
        f"- table4_method_comparison.csv: {'OK' if checklist['table4_method_comparison_csv'] else 'MISSING'}",
        f"- table4_method_comparison.md: {'OK' if checklist['table4_method_comparison_md'] else 'MISSING'}",
        f"- core_counts.json: {'OK' if checklist['core_counts_json'] else 'MISSING'}",
        "",
        f"Table 4 status: {table4_message}",
        "",
        "If Table 4 is missing, run:",
        "- python scripts/legacy_methods/top2vec_modeling.py",
        "- python scripts/legacy_methods/top2vec_validation.py",
        "- python scripts/legacy_methods/generate_table4_method_comparison.py",
    ]
    (out_reports / "paper_bundle_checklist.md").write_text("\n".join(lines), encoding="utf-8")

    print(f"Saved paper outputs to {paper_outputs}.")
    if table4_available:
        print("Table 4 is included in the consolidated paper bundle.")
    else:
        print(f"Warning: {table4_message}")


if __name__ == "__main__":
    main()
